on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Mostrar informacion y construir imagen
        run: |
          echo "Building Docker image..."
          docker build -t dockermazin/hola-mundo:5 .
      - name: Mostrar informacion y construir imagen
        run: |
          echo "Push Docker image ...."
          docker push dockermazin/hola-mundo:5
